baseURL = "/"
title = "Humour et Délire"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2021-{year} Humour et Délire. Aucun Copyright pour le contenue sur se site."

# Multilingual mode
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
